Increase code coverage
yiisoft/profiler pull request #19
Opened 2020-12-03 00:16 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2020-12-04 18:55 UTC, samdark requested changes

2020-12-04 18:55 UTC, samdark commented on composer.json
> +        "yiisoft/aliases": "^1.1.1"
That's not dev dependency and, if it's going to be used, has to be moved to `require`.

2020-12-04 18:55 UTC, samdark commented on src/Profiler.php
> +    protected function logCategoryMessages(string $category, array $categoryMessages): void
Does it make sense for it to be protected? How about making `Profiler` final?

2020-12-04 18:55 UTC, samdark commented on src/Profiler.php
> +        $message = array_merge(
Logger was refactored by @devanych so messages are objects and in resulted in increased performance. Maybe it worth doing the same here.

2020-12-08 23:51 UTC, samdark commented
Looks alright but Psalm issues should be fixed.

2020-12-09 07:04 UTC, rustamwin commented
> Looks alright but Psalm issues should be fixed.

Done.

2020-12-09 12:07 UTC, samdark requested changes

2020-12-09 12:07 UTC, samdark commented on src/FileTarget.php
>      protected function resolveFilename(): string
Since class is final, it doesn't make sense to have a protected method.

2020-12-09 12:07 UTC, samdark commented on src/LogTarget.php
> +final class LogTarget extends Target
Looks like `getLogLevel()` method isn't used anywhere except tests. I don't see it being useful at all. How about removing it?

2020-12-09 12:07 UTC, samdark commented on src/Profiler.php
> +final class Profiler implements ProfilerInterface
Many methods of the class aren't used anywhere except tests. Are these useful?

- `getEnabled()`. If it's needed, it shoud be called `isEnabled()`.
- `getMessages()`.
- `setMessages()`.
- `setTargets()`, `addTarget()` - do we want to dynamically change targets after Profiler instance was created?

2020-12-09 12:07 UTC, samdark commented on src/Target.php
>      public bool $enabled = true;
That doesn't look good. It's better to have a pair of `setEnabled()` and `isEnabled()`.

2020-12-09 14:48 UTC, rustamwin commented on src/Profiler.php
> +final class Profiler implements ProfilerInterface
- `getEnabled()` renamed to `isEnabled()`.
- `getMessages()` let's leave it.
- `setMessages()`, `setTargets()`, `addTarget()` removed.

2020-12-10 10:31 UTC, samdark approved these changes

2020-12-10 10:32 UTC, merged

2020-12-10 10:32 UTC, samdark commented
👍