Fix static analysis tests
yiisoft/profiler pull request #42
Opened 2022-01-11 15:59 UTC by devanych

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2022-01-11 17:41 UTC, vjik approved these changes

2022-01-11 21:54 UTC, samdark requested changes

2022-01-11 21:54 UTC, samdark commented on CHANGELOG.md
> +- Chg #42: Forbidden pass context with "beginMemory" or "beginTime" keys to `Profiler::end()` (vjik)
```suggestion
- Bug #42: Forbid passing context with "beginMemory" or "beginTime" keys to `Profiler::end()` (vjik)
```

2022-01-11 21:54 UTC, samdark commented on CHANGELOG.md
> +- Bug #42: Checking that category of message is a string (vjik)
```suggestion
- Bug #42: Check that category of message is a string (vjik)
```

2022-01-11 21:54 UTC, samdark commented on src/Profiler.php
> +     * a single {@see TargetInterface} profiling target instance.
It was OK:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/47294/149027024-e7b806d0-e0ff-4038-854e-5aab57b0957f.png">

2022-01-11 21:54 UTC, samdark commented on src/Profiler.php
> +            throw new InvalidArgumentException('Forbidden to override "beginTime" in context.');
```suggestion
            throw new InvalidArgumentException('It is forbidden to override "beginTime" in context.');
```

2022-01-11 21:54 UTC, samdark commented on src/Profiler.php
> +            throw new InvalidArgumentException('Forbidden to override "beginMemory" in context.');
```suggestion
            throw new InvalidArgumentException('It is forbidden to override "beginMemory" in context.');
```

2022-01-11 21:54 UTC, samdark commented on tests/ProfilerTest.php
> +            'Forbidden to override "beginTime" in context.'
```suggestion
            'It is forbidden to override "beginTime" in context.'
```

2022-01-11 21:54 UTC, samdark commented on tests/ProfilerTest.php
> +            'Forbidden to override "beginMemory" in context.'
```suggestion
            'It is forbidden to override "beginMemory" in context.'
```

2022-01-12 18:00 UTC, vjik commented on tests/ProfilerTest.php
> +            'Forbidden to override "beginMemory" in context.'
done

2022-01-12 18:00 UTC, vjik commented on tests/ProfilerTest.php
> +            'Forbidden to override "beginTime" in context.'
done

2022-01-12 18:00 UTC, vjik commented on src/Profiler.php
> +            throw new InvalidArgumentException('Forbidden to override "beginMemory" in context.');
done

2022-01-12 18:00 UTC, vjik commented on src/Profiler.php
> +            throw new InvalidArgumentException('Forbidden to override "beginTime" in context.');
done

2022-01-12 18:01 UTC, vjik commented on CHANGELOG.md
> +- Chg #42: Forbidden pass context with "beginMemory" or "beginTime" keys to `Profiler::end()` (vjik)
fixed

2022-01-17 20:37 UTC, samdark approved these changes

2022-01-17 20:37 UTC, samdark commented on CHANGELOG.md
> +- Bug #42: Check that category of message is a string (vjik)
```suggestion
- Bug #42: Check that category of a message is a string (vjik)
```

2022-01-17 20:38 UTC, merged

2022-01-17 20:38 UTC, samdark commented
:+1