Update readme.md requirements
yiisoft/profiler pull request #50
Opened 2022-07-13 07:27 UTC by DplusG

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #40

2022-07-13 19:17 UTC, samdark requested changes

2022-07-13 19:17 UTC, samdark commented on README.md
> +- If in `yiisoft/aliases` configuration will be no alias `@runtime`, then application throws error `Invalid path alias: @runtime/profiling/{date}-{time}.txt`
That should be in installation section. That's not a requirement but an installation step.

2022-07-20 10:51 UTC, vjik requested changes

2022-07-20 10:51 UTC, vjik commented on README.md
> +- If in `yiisoft/aliases` configuration will be no alias `@runtime`, then application throws error `Invalid path alias: @runtime/profiling/{date}-{time}.txt`
We should describe about `@runtime` in params and suggest change it (how and where) if need.

2022-07-29 08:04 UTC, samdark commented on README.md
> +Than install the following package `yiisoft/aliases` via composer:
```suggestion
If there will be no `@runtime` alias in `yiisoft/aliases` configuration defined, application will throw "Invalid path alias" error.

To solve it, install the following package `yiisoft/aliases` via composer:

```

2022-07-29 08:04 UTC, samdark approved these changes

2022-07-29 08:04 UTC, merged

2022-07-29 08:04 UTC, samdark commented
Thanks!